// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tyfvbqpynflfhbukluvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5ZnZicXB5bmZsZmhidWtsdXZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MDczNzEsImV4cCI6MjA2ODE4MzM3MX0.XmvoOpIqa32uoUhT5islUlyY0vYLll-RdhLtdmhn58o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});